language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7

dist: xenial
os: linux

addons:
  apt:
    sources:
    - trusty
    - deadsnakes
    - sourceline: 'ppa:sergey-dryabzhinsky/packages'

install:
- sudo apt-get update -qq
- sudo apt-get install -qq libzstd-dev

script:
- python setup.py test
- python setup.py clean -a
- env PYZSTD_LEGACY=1 python setup.py --pyzstd-legacy test
- python setup.py clean -a
- env LEGACY=1 PYZSTD_LEGACY=1 python setup.py --legacy --pyzstd-legacy test
- python setup.py clean -a
- python setup.py --external test
- python setup.py clean -a
