os: linux
dist: xenial
language: python
matrix:
  include:
    - name: "Python 2.7 Xenial AMD64"
      python: 2.7
      dist: xenial
    - name: "Python 3.4 Xenial AMD64"
      python: 3.4
      dist: xenial
    - name: "Python 3.5 Xenial AMD64"
      python: 3.5
      dist: xenial
    - name: "Python 3.6 Xenial AMD64"
      python: 3.6
      dist: xenial
    - name: "Python 3.7 Xenial AMD64"
      python: 3.7
      dist: xenial
    - name: "Python 3.8 Xenial AMD64"
      python: 3.8
      dist: xenial
    - name: "Python 3.9 Bionic AMD64"
      python: 3.9
      dist: bionic
    - name: "Python 3.10 Bionic AMD64"
      python: 3.10
      dist: bionic

    - name: "Python 2.7 Xenial ARM64"
      python: 2.7
      arch: arm64
      dist: xenial
    - name: "Python 3.4 Xenial ARM64"
      python: 3.4
      arch: arm64
      dist: xenial
    - name: "Python 3.5 Xenial ARM64"
      python: 3.5
      arch: arm64
      dist: xenial
    - name: "Python 3.6 Xenial ARM64"
      python: 3.6
      arch: arm64
      dist: xenial
    - name: "Python 3.7 Xenial ARM64"
      python: 3.7
      arch: arm64
      dist: xenial
    - name: "Python 3.8 Xenial ARM64"
      python: 3.8
      arch: arm64
      dist: xenial
    - name: "Python 3.9 Bionic ARM64"
      python: 3.9
      arch: arm64
      dist: bionic
    - name: "Python 3.10 Bionic ARM64"
      python: 3.10
      arch: arm64
      dist: bionic
addons:
  apt:
    sources:
    - sourceline: 'ppa:sergey-dryabzhinsky/packages'

install:
- sudo apt-get update -qq
- sudo apt-get install -qq libzstd-dev

script:
- python setup.py test
- python setup.py clean -a
- env LEGACY=1 python setup.py --legacy test
- python setup.py clean -a
- python setup.py --external test || true
- python setup.py clean -a
